name: 4 Workflow
on: 
  workflow_run:
    workflows: ["third Workflow"]
    types:
     - 
        completed

jobs:
  run-hello-world: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Print Hello World        
        run: echo "Hello World"
      